export const demoTrip = {
  name: "Grande rota pela Europa",
  currency: "EUR" as const,
  travelersCount: 2,
  stops: [
    {
      placeName: "Berlim",
      country: "Alemanha",
      region: "Berlim",
      formattedAddress: "Berlim, Alemanha",
      latitude: 52.52,
      longitude: 13.405,
      nightlyCost: 120,
      nights: 3,
      notes: "Museus, Mitte e Portão de Brandemburgo.",
    },
    {
      placeName: "Budapeste",
      country: "Hungria",
      region: "Budapeste",
      formattedAddress: "Budapeste, Hungria",
      latitude: 47.4979,
      longitude: 19.0402,
      nightlyCost: 85,
      nights: 3,
      notes: "Termas e passeio pelo Danúbio.",
    },
    {
      placeName: "Zagreb",
      country: "Croácia",
      region: "Cidade de Zagreb",
      formattedAddress: "Zagreb, Croácia",
      latitude: 45.815,
      longitude: 15.9819,
      nightlyCost: 75,
      nights: 2,
      notes: "Centro histórico e mercado Dolac.",
    },
    {
      placeName: "Sarajevo",
      country: "Bósnia e Herzegovina",
      region: "Cantão de Sarajevo",
      formattedAddress: "Sarajevo, Bósnia e Herzegovina",
      latitude: 43.8563,
      longitude: 18.4131,
      nightlyCost: 65,
      nights: 2,
      notes: "Baščaršija e gastronomia local.",
    },
    {
      placeName: "Podgorica",
      country: "Montenegro",
      region: "Podgorica",
      formattedAddress: "Podgorica, Montenegro",
      latitude: 42.4304,
      longitude: 19.2594,
      nightlyCost: 60,
      nights: 2,
      notes: "Base para explorar o interior de Montenegro.",
    },
    {
      placeName: "Bari",
      country: "Itália",
      region: "Apúlia",
      formattedAddress: "Bari, Itália",
      latitude: 41.1171,
      longitude: 16.8719,
      nightlyCost: 95,
      nights: 2,
      notes: "Bari Vecchia e orla do Adriático.",
    },
    {
      placeName: "Catânia",
      country: "Itália",
      region: "Sicília",
      formattedAddress: "Catânia, Itália",
      latitude: 37.5079,
      longitude: 15.083,
      nightlyCost: 90,
      nights: 3,
      notes: "Centro barroco e passeio ao Etna.",
    },
    {
      placeName: "Roma",
      country: "Itália",
      region: "Lácio",
      formattedAddress: "Roma, Itália",
      latitude: 41.9028,
      longitude: 12.4964,
      nightlyCost: 140,
      nights: 4,
      notes: "Roma antiga, Vaticano e Trastevere.",
    },
    {
      placeName: "Milão",
      country: "Itália",
      region: "Lombardia",
      formattedAddress: "Milão, Itália",
      latitude: 45.4642,
      longitude: 9.19,
      nightlyCost: 150,
      nights: 3,
      notes: "Duomo, Brera e encerramento da rota.",
    },
  ],
};
